# Generated by Django 6.0.7 on 2026-08-02 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='도구 이름')),
                ('description', models.TextField(verbose_name='도구 설명')),
                ('icon', models.CharField(default='🛠️', max_length=10, verbose_name='아이콘 이모지')),
                ('price', models.PositiveIntegerField(default=3000, verbose_name='가격(원)')),
                ('purchase_count', models.PositiveIntegerField(default=0, verbose_name='총 선택/구매 횟수')),
                ('tool_link', models.URLField(blank=True, help_text='예: https://notion.site/... 또는 외부 앱 URL', null=True, verbose_name='도구 실행 링크')),
                ('access_code', models.CharField(blank=True, help_text='구매자에게만 제공할 비밀번호', max_length=100, null=True, verbose_name='접속 비밀번호/키')),
                ('usage_instruction', models.TextField(blank=True, null=True, verbose_name='도구 사용 방법 설명글')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-purchase_count'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='문의 제목')),
                ('content', models.TextField(verbose_name='문의 내용')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='관리자 답변')),
                ('status', models.CharField(choices=[('pending', '답변 대기'), ('completed', '답변 완료')], default='pending', max_length=10, verbose_name='처리 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='문의일')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='답변일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='문의자')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_notice', models.BooleanField(default=False, verbose_name='공지글 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('usage_count', models.IntegerField(default=0, verbose_name='누적 사용 횟수')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tool')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.post')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='닉네임')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserToolAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_selected_tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_users', to='main.tool', verbose_name='선택한 무료 도구')),
                ('paid_tools', models.ManyToManyField(blank=True, related_name='paid_users', to='main.tool', verbose_name='결제한 도구들')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tool_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
