# Generated by Django 6.0.7 on 2026-07-27 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='도구 이름')),
                ('description', models.TextField(verbose_name='도구 설명')),
                ('icon', models.CharField(default='🛠️', max_length=10, verbose_name='아이콘 이모지')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='총 사용 횟수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-usage_count'],
            },
        ),
        migrations.CreateModel(
            name='UserToolAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_selected_tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_users', to='main.tool', verbose_name='선택한 무료 도구')),
                ('paid_tools', models.ManyToManyField(blank=True, related_name='paid_users', to='main.tool', verbose_name='결제한 도구들')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tool_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
