# Generated by Django 6.0.7 on 2026-07-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['-purchase_count']},
        ),
        migrations.RemoveField(
            model_name='tool',
            name='usage_count',
        ),
        migrations.AddField(
            model_name='tool',
            name='access_code',
            field=models.CharField(blank=True, help_text='구매자에게만 제공할 비밀번호', max_length=100, null=True, verbose_name='접속 비밀번호/키'),
        ),
        migrations.AddField(
            model_name='tool',
            name='purchase_count',
            field=models.PositiveIntegerField(default=0, verbose_name='총 선택/구매 횟수'),
        ),
        migrations.AddField(
            model_name='tool',
            name='tool_link',
            field=models.URLField(blank=True, help_text='예: https://notion.site/... 또는 외부 앱 URL', null=True, verbose_name='도구 실행 링크'),
        ),
        migrations.AddField(
            model_name='tool',
            name='usage_instruction',
            field=models.TextField(blank=True, null=True, verbose_name='도구 사용 방법 설명글'),
        ),
    ]
