# Generated by Django 6.0.7 on 2026-07-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_tool_options_remove_tool_usage_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='price',
            field=models.PositiveIntegerField(default=3000, verbose_name='가격(원)'),
        ),
    ]
